<body>
<div class="wrapper wrapp product_catalog" id="wrapper">
  <header>
    <div class="container">
      <?php include(__DIR__ . "/../common/header.php"); ?>
    </div>
  </header>
  <section class="main_content">
    <a id="page_id" style="display: none">search</a>
    <div class="container">
      <?php include(__DIR__ . "/../common/search_form.php"); ?>
      <div class="crumbs_wrap">
        <ol data-reactroot="" class="breadcrumb my_breadcrumbs">
          <li><a href="/"><span>Головна</span></a>
            <i class="fa fa-angle-right" aria-hidden="true"></i></li>
          <li class="breadcrumb-country">
            <a href="#"></a>
          </li>
          <li class="breadcrumb-town">
            <a href="#"></a>
          </li>
          <li class="breadcrumb-hotel active">Готелі</li>
        </ol>
      </div>
      <div class="row">
        <?php include(__DIR__ . "/../common/filter.php"); ?>
        <?php include(__DIR__ . "/../common/catalog.php"); ?>
      </div>
    </div>
  </section>

</div>
<footer>
  <?php include(__DIR__ . '/../common/footer.php'); ?>
</footer>
<?php include(__DIR__ . '/../common/footer_js.php'); ?>
</body>
