<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("attributes", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create attributes
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "attributes/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldObjId" class="col-sm-2 control-label">Obj</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("obj_id", "type" => "number", "class" => "form-control", "id" => "fieldObjId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAttrId" class="col-sm-2 control-label">Attr</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("attr_id", "type" => "number", "class" => "form-control", "id" => "fieldAttrId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTableId" class="col-sm-2 control-label">Table</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("table_id", "type" => "number", "class" => "form-control", "id" => "fieldTableId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldVal" class="col-sm-2 control-label">Val</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("val", "size" => 30, "class" => "form-control", "id" => "fieldVal")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldValUk" class="col-sm-2 control-label">Val Of Uk</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("val_uk", "size" => 30, "class" => "form-control", "id" => "fieldValUk")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
