<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag;

?>

<div class="row">
  <nav>
    <ul class="pager">
      <li class="previous">
        <?php
//          $sLink = strlen($aTable['adm_link'])>0?$aTable['adm_link']:($aTable['name'].'/index');
//          $sLink = Hl::url($sLink);
//          echo $this->tag->linkTo( array( "{$sLink}", Hl::$t->_('Go Back') ) );
          echo '<a id="go_back" onclick="backAction()">'.Hl::$t->_('Go Back').'</a>';
        ?>
      </li>
      <li class="next">
        <?php
          $sLink = Hl::url($aTable['name']);
          echo $this->tag->linkTo( array( "{$sLink}/create",
          Hl::$t->_('Create')." " ) ); ?></li>
    </ul>
  </nav>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2><?php echo $aTable['note'.Hl::$pstfx];
        if ($this->flashSession->has())
        echo '<div>'.$this->flashSession->output().'</div>';
        ?>
      </h2>
      <?php //include('admin_settings.php'); ?>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <!--p class="text-muted font-13 m-b-30">
        This example shows FixedHeader being styling by the Bootstrap CSS framework.
      </p-->
      <div id="datatable-fixed-header_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
        <div class="row">
          <div class="col-sm-6">
            <div class="dataTables_length" id="datatable-fixed-header_length"><label>
                <?=Hl::$t->_('Show')?>
                <select
                  name="datatable-fixed-header_length" aria-controls="datatable-fixed-header"
                  class="form-control input-sm" onchange="setPerPage(this)" href="/option?per_page=">
                  <?php foreach ([10,25,50,100] as $p) {
                    echo '<option value="'.$p.'"'.($p==$page->limit?' selected':'').'>'.$p.
                      '</option>';
                  } ?>
                </select> <?=Hl::$t->_('entries')?></label></div>
          </div>
          <div class="col-sm-6">
            <div id="datatable-fixed-header_filter" class="dataTables_filter">
              <label><?= $this->tag->linkTo( Hl::url( "{$aTable['name']}/search" ), Hl::$t->_("Search") )?>:
                <input
                  type="search" class="form-control input-sm" placeholder=""
                  aria-controls="datatable-fixed-header"></label></div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <table id="datatable-fixed-header"
                   class="table table-striped table-bordered dataTable no-footer" role="grid"
                   aria-describedby="datatable-fixed-header_info">
              <thead>
              <tr>
                <?php
                $aFields = $aTable['name']::fields();
                if (!is_array($aFields))
                foreach ( $page->items[0] as $ki=>$vi )
                  $aFields[$ki] = ['label'=>$ki];
                foreach ( $aFields as $kf => $vf )
                  if (!isset($vf['inaccessible']))
                  if (!isset($vf['hideInGrid']))
                  if (!isset($vf['hidden']))
                  if (isset($vf[ 'label' ]))
                    echo '<th>' . $vf[ 'label' ] . '</th>';
                  else
                    echo '<th>' . $kf . '</th>';
                ?>
                <th><?=Hl::$t->_('Actions')?></th>
              </tr>
              </thead>
              <tbody>
              <?php
                if (!isset($aAttrs))
                  $aAttrs = Attrtypes::all();
                foreach ( $page->items as $item ): ?>
                <tr>
                  <?php
                  $aItems = get_object_vars( $item );
                  foreach ( $aFields as $k => $l )
                    if (!isset($l['inaccessible']))
                    if (!isset($l['hideInGrid']))
                    if (!isset($l['hidden'])) {
                      $sFieldVal = $aItems[$k];

                      if (isset($l[ 'control' ]) && $l[ 'control' ] == 'checkbox') {
                        $aOptions = [$k.'_'.$aItems['id']];
                        if ($sFieldVal > 0)
                          $aOptions['checked'] = 'checked';
                        $aOptions['disabled'] = 'disabled';
                        $sFieldVal = $this->tag->checkField($aOptions);
                      }

                      if ($k == 'attr_id' || Hl::aSafe($l,'foreign') == 'attrtypes') {
                        //Розшифровка з масиву атрибутів
                        $sFieldVal = Hl::aSafe($aAttrs, [$aItems[$k], 'name']);
                      }
                      elseif (isset($l['foreign']) && strlen($l['foreign']) > 0) {
                        if (isset($l['foreign_show'])) //яке поле показувати
                          $field2show = $l['foreign_show'];
                        else
                          $field2show = 'name';
                        $sForeign = Hl::aSafe($aForeign,[$l['foreign'],$aItems[$k],$field2show],false);
                        if ($sForeign)
                          $sFieldVal = $sForeign;
                      }

                      if (strlen($sFieldVal) > 300) //Скорочуємо текст
                        $sFieldVal = Hl::trimText($sFieldVal,300);

                      echo '<td>' . $sFieldVal . '</td>';
                    }
                  ?>
                  <td>
                    <?php
                      echo Hl::buttons($item->id,$aTable['name'],isset($aButtons)?$aButtons:null)
                    ?>
                  </td>
                </tr>
              <?php endforeach; ?>
              </tbody>
            </table>
          </div>
        </div>
        <?php include __DIR__ . '/../common/table_footer.php'; ?>
      </div>
    </div>
  </div>
</div>

<!--div class="row">
  <div class="col-sm-1">
    <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
      <?php //echo $page->current, "/", $page->total_pages ?>
    </p>
  </div>
  <div class="col-sm-11">
    <nav>
      <ul class="pagination">
        <?php //if ( $page->current > 1 && $page->total_pages > 1 ) { ?>
          <li><?php //echo $this->tag->linkTo( Hl::url( $aTable['name'] ), "First" ) ?></li>
          <li><?php //echo $this->tag->linkTo( Hl::url( $aTable['name']."?page=" . $page->before ), "Previous" ) ?></li>
        <?php //} ?>
        <?php //if ( $page->current < $page->total_pages ) { ?>
          <li><?php //echo $this->tag->linkTo( Hl::url( $aTable['name']."?page=" . $page->next ), "Next" ) ?></li>
          <li><?php //echo $this->tag->linkTo( Hl::url( $aTable['name']."?page=" . $page->last ), "Last" ) ?></li>
        <?php //} ?>
      </ul>
    </nav>
  </div>
</div-->
