<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("attrtypes", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>
              <?php
                echo $aTable['note'.Hl::$pstfx];
                if ($this->flashSession->has())
                  echo '<div>'.$this->flashSession->output().'</div>';
              ?>
                <!--small>different form elements</small-->
            </h2>
            <?php //include('/../admin/admin_settings.php'); ?>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br>
          <?php
          echo $this->tag->form(
            array(
              "attrtypes/create",
              "autocomplete" => "off",
              "id" => "new-".$aTable['name'],
              "class" => "form-horizontal  form-label-left",
            )
          );
          ?>
            <!--form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" novalidate=""-->

          <?php
            $aFields = $aTable['name']::fields();
          
            foreach ( $aFields as $kf=>$vf )
              if (!isset($vf['hidden']))
              {
              $fieldName = Hl::Uc($kf);
          ?>
              <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12"
                         for="field<?=$fieldName?>">
                    <?php
                      if (isset($vf['label']))
                        echo $vf['label'];
                      else
                        echo $fieldName;
                      if (isset($vf['required']))
                        echo '<span class="">*</span>';
                    ?>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php
                      $aOptions = [$kf,
                        "class" => "form-control col-md-7 col-xs-12",
                        "id" => "field".$fieldName];
                      if (isset($vf['required']))
                        $aOptions["required"] = "required";
                      if (isset($vf['size']))
                        $aOptions["size"] = $vf['size'];
                      echo $this->tag->textField($aOptions);
                    ?>
                  </div>
              </div>
          <?php } ?>
                <!--div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Gender</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div id="gender" class="btn-group" data-toggle="buttons">
                            <label class="btn btn-default" data-toggle-class="btn-primary"
                                   data-toggle-passive-class="btn-default">
                                <input type="radio" name="gender" value="male" data-parsley-multiple="gender"> &nbsp;
                                Male &nbsp;
                            </label>
                            <label class="btn btn-primary" data-toggle-class="btn-primary"
                                   data-toggle-passive-class="btn-default">
                                <input type="radio" name="gender" value="female" data-parsley-multiple="gender"> Female
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Date Of Birth <span
                            class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="birthday" class="date-picker form-control col-md-7 col-xs-12" required="required"
                               type="text">
                    </div>
                </div-->
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                      <?php
                      echo $this->tag->submitButton(array(Hl::$t->_('Cancel'), "class" => "btn btn-primary"));
                      echo $this->tag->submitButton(array(Hl::$t->_('Save'), "class" => "btn btn-default  btn-success")); ?>
                    </div>
                </div>

              <?php echo $this->tag->endForm(); ?>
        </div>
    </div>
</div>

