<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous">
              <?php
              /*
              if (isset($backLink))
                $sLink = $backLink;
              else
                $sLink = strlen($aTable['adm_link'])>0?$aTable['adm_link']:$aTable['name'];
              echo $this->tag->linkTo([$sLink,
                Hl::$t->_('Go Back'),'id' => 'go_back']);
              */
              echo '<a id="go_back" onclick="backAction()">'.Hl::$t->_('Go Back').'</a>';
              ?></li>

        </ul>
    </nav>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>
                <?php
                echo $aTable['note'.Hl::$pstfx];
                echo '<small>('.Hl::$t->_($sOperation).')</small>';
                if ($this->flashSession->has())
                    echo '<div>'.$this->flashSession->output().'</div>';
                ?>
                <!--small>different form elements</small-->
            </h2>
            <?php //include(__DIR__.'/../admin/admin_settings.php'); ?>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br>
            <?php
            if (!isset($bError)) {
              echo $this->tag->form(
                array(
                  Hl::url($aTable['name']) . "/".$sOperation.'go',
                  "autocomplete" => "off",
                  "id" => "new-" . $aTable['name'],
                  "class" => "form-horizontal  form-label-left",
                )
              );
              ?>
              <!--form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" novalidate=""-->

              <?php
              $sModel = ucfirst($aTable['name']);
              if (!isset($aFields))
                $aFields = $sModel::fields();
              foreach ($aFields as $kf => $vf) {
                  if (isset($vf['inaccessible'])||
                      isset($vf['noEdit'])) continue;
                  $fieldName = Hl::Uc($kf);
                  if (isset($vf['hidden'])) $sStyle = 'style="display:none"';
                  else $sStyle = '';
                  ?>
                  <div class="form-group" <?=$sStyle?>>
                    <label class="control-label col-md-3 col-sm-3 col-xs-12"
                           for="field<?= $fieldName ?>">
                      <?php
                      if (isset($vf['label']))
                        echo $vf['label'];
                      else
                        echo $fieldName;
                      if (isset($vf['required']))
                        echo '<span class="">*</span>';
                      ?>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <?php
                      if (isset($vf['foreign'])) {
                        if (isset($vf['foreign_show'])) //яке поле показувати
                          $field2show = $vf['foreign_show'];
                        else
                          $field2show = 'name';
                        if (isset($vf['foreign_filter']))
                          $aWhere = ['where' => $vf['foreign_filter']];
                        else
                          $aWhere = null;
                        if (isset($vf['foreign_order']))
                          $aWhere['order'] = $vf['foreign_order'];
                        $aSelectValues = Hl::q2sel(HT::sel($vf['foreign'],$aWhere),$field2show);
                        if (!$aSelectValues)
                          $aSelectValues = [''=>Hl::$t->_('Not found')];
                        $aOptions = [$kf,
                          $aSelectValues
                        ];
                        if ($sOperation == 'search' || !isset($vf['required'])) //Або пошук, або не обов'язкове поле
                          $aOptions["useEmpty"] = true;
                      }
                      else
                        $aOptions = [$kf];
                      $aOptions["id"] = "field" . $fieldName;
                      if (isset($vf['class']))
                        $aOptions["class"] = $vf['class'];
                      else
                        $aOptions["class"] = "form-control col-md-7 col-xs-12";

                      //Для прямого копіювання назви значення
                      foreach (['required','readonly','disabled'] as $v)
                        if (isset($vf[$v]))
                          $aOptions[$v] = $v;

                      //Для копіювання значення
                      foreach (['size','onChange'] as $v)
                      if (isset($vf[$v]))
                        $aOptions[$v] = $vf[$v];

                      if (isset($aItem))
                      if ($val = Hl::aSafe($aItem,$kf,false))
                        $aOptions['value'] = $val;

                      if (isset($vf['hidden'])) {
                        if ($sOperation != 'search')
                          echo $this->tag->hiddenField($aOptions);
                      }
                      elseif (isset($vf['foreign'])) {
                        unset($aOptions['size']);
                        echo $this->tag->selectStatic($aOptions);
                      }
                      elseif (isset($vf['control']) && $vf['control'] == 'checkbox') {
                        if (isset($aOptions['value']) && $aOptions['value'] > 0)
                          $aOptions['checked'] = 'checked';
                        if ($sOperation != 'search') {
                          $aOptions['value'] = '0';
                          echo $this->tag->hiddenField($aOptions);
                        }
                        $aOptions['value'] = '1';
                        echo $this->tag->checkField($aOptions);
                      }
                      else
                        echo $this->tag->textField($aOptions);
                      if (isset($vf['afterControl']))
                        echo $vf['afterControl'];
                      ?>
                    </div>
                  </div>
                <?php }
                if (isset($aTable['options']) && is_array($aTable['options']))
                  include('admin_edit_af.phtml')
              ?>
              <!--div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12">Gender</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <div id="gender" class="btn-group" data-toggle="buttons">
                          <label class="btn btn-default" data-toggle-class="btn-primary"
                                 data-toggle-passive-class="btn-default">
                              <input type="radio" name="gender" value="male" data-parsley-multiple="gender"> &nbsp;
                              Male &nbsp;
                          </label>
                          <label class="btn btn-primary" data-toggle-class="btn-primary"
                                 data-toggle-passive-class="btn-default">
                              <input type="radio" name="gender" value="female" data-parsley-multiple="gender"> Female
                          </label>
                      </div>
                  </div>
              </div>
              <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12">Date Of Birth <span
                          class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <input id="birthday" class="date-picker form-control col-md-7 col-xs-12" required="required"
                             type="text">
                  </div>
              </div-->
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                  <?php
                  /*echo $this->tag->submitButton(
                    [Hl::$t->_('Cancel'), "class" => "btn btn-primary",
                      "onclick"=>'window.location="'.Hl::url($aTable['name']).'"',
                      "onsubmit"=>'return false',
                    ]);*/
                  if ($sOperation == 'search')
                    echo '<input type="button" value="'.Hl::$t->_('Clear').
                      '" class="btn btn-primary" onclick="$(\'.form-control\').val(\'\')">';
                  echo '<input type="button" value="'.Hl::$t->_('Cancel').
                    '" class="btn btn-primary" onclick="$(\'#go_back\').click()">';
                  echo $this->tag->submitButton(
                    [Hl::$t->_(ucfirst($sOperation)),
                      "class" => "btn btn-default  btn-success"]); ?>
                </div>
              </div>

            <?php
              echo $this->tag->endForm();
            }
            ?>
        </div>
    </div>
</div>
