<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag;

?>

<div class="row">
  <nav>
    <ul class="pager">
      <li class="previous"><?php echo $this->tag->linkTo( array( "{$oData['name']}/index", Hl::$t->_('Go Back') ) ); ?></li>
      <li class="next"><?php echo $this->tag->linkTo( array( "{$oData['name']}/new",
          Hl::$t->_('Create')." " ) ); ?></li>
    </ul>
  </nav>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2><?=$oData['note'.Hl::$pstfx]?></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
             aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a>
            </li>
            <li><a href="#">Settings 2</a>
            </li>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <!--p class="text-muted font-13 m-b-30">
        This example shows FixedHeader being styling by the Bootstrap CSS framework.
      </p-->
      <div id="datatable-fixed-header_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
        <div class="row">
          <div class="col-sm-6">
            <div class="dataTables_length" id="datatable-fixed-header_length"><label>
                <?=Hl::$t->_('Show')?>
                <select
                  name="datatable-fixed-header_length" aria-controls="datatable-fixed-header"
                  class="form-control input-sm" onchange="setPerPage(this)" href="/option?per_page=">
                  <?php foreach ([10,25,50,100] as $p) {
                    echo '<option value="'.$p.'"'.($p==$page->limit?' selected':'').'>'.$p.
                      '</option>';
                  } ?>
                </select> <?=Hl::$t->_('entries')?></label></div>
          </div>
          <div class="col-sm-6">
            <div id="datatable-fixed-header_filter" class="dataTables_filter">
              <label><?= $this->tag->linkTo( Hl::url( "{$oData['name']}/search" ), "Search")?>:
                <input
                  type="search" class="form-control input-sm" placeholder=""
                  aria-controls="datatable-fixed-header"></label></div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <table id="datatable-fixed-header"
                   class="table table-striped table-bordered dataTable no-footer" role="grid"
                   aria-describedby="datatable-fixed-header_info">
              <thead>
              <tr>
                <?php
                $aFields = Attrtypes::fields();
                foreach ( $aFields as $l )
                  echo '<th>' . $l[ 'label' ] . '</th>';
                ?>
                <th><?=Hl::$t->_('Actions')?></th>
              </tr>
              </thead>
              <tbody>
              <?php foreach ( $page->items as $item ): ?>
                <tr>
                  <?php
                  $aItems = get_object_vars( $item );
                  foreach ( $aFields as $k => $l )
                    echo '<td>' . $aItems[ $k ] . '</td>';
                  ?>
                  <td><?=Hl::buttons($item->id,$oData['name'])?>
                  </td>
                </tr>
              <?php endforeach; ?>
              </tbody>
            </table>
          </div>
        </div>
        <?php include __DIR__ . '/../common/table_footer.php'; ?>
      </div>
    </div>
  </div>
</div>

<!--div class="row">
  <div class="col-sm-1">
    <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
      <?php echo $page->current, "/", $page->total_pages ?>
    </p>
  </div>
  <div class="col-sm-11">
    <nav>
      <ul class="pagination">
        <?php if ( $page->current > 1 && $page->total_pages > 1 ) { ?>
          <li><?php echo $this->tag->linkTo( Hl::url( $oData['name'] ), "First" ) ?></li>
          <li><?php echo $this->tag->linkTo( Hl::url( $oData['name']."?page=" . $page->before ), "Previous" ) ?></li>
        <?php } ?>
        <?php if ( $page->current < $page->total_pages ) { ?>
          <li><?php echo $this->tag->linkTo( Hl::url( $oData['name']."?page=" . $page->next ), "Next" ) ?></li>
          <li><?php echo $this->tag->linkTo( Hl::url( $oData['name']."?page=" . $page->last ), "Last" ) ?></li>
        <?php } ?>
      </ul>
    </nav>
  </div>
</div-->
