<?php include(__DIR__."/../common/doctype.php"); ?>
<head>
  <?php include 'admin_head.php';?>
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <?php include 'admin_left.php';?>

      <?php include 'admin_header.php';?>

      <!-- page content -->
      <div class="right_col" role="main">
        <?php //include 'admin_content.php';?>
      </div>
      <!-- /page content -->

      <?php include 'admin_footer.php';?>

    </div>
  </div>

  <?php include 'admin_scripts.php';?>

</body>

</html>
