<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("toplists", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create toplists
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "toplists/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldAttrId" class="col-sm-2 control-label">Attr</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("attr_id", "type" => "number", "class" => "form-control", "id" => "fieldAttrId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldObjId" class="col-sm-2 control-label">Obj</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("obj_id", "type" => "number", "class" => "form-control", "id" => "fieldObjId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSort" class="col-sm-2 control-label">Sort</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("sort", "type" => "number", "class" => "form-control", "id" => "fieldSort")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdated" class="col-sm-2 control-label">Updated</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("updated", "size" => 30, "class" => "form-control", "id" => "fieldUpdated")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
