<?php include(__DIR__ . "/../common/doctype.php"); ?>
<head>
  <?php include(__DIR__ . '/../common/head.php'); ?>
</head>
<div class="wrapper wrapp contacts_page" id="wrapper">
  <?php //include( "/../common/sidebar-menu.php" ); ?>
  <header>
    <div class="container">
      <?php include(__DIR__ . "/../common/header.php"); ?>
    </div>
  </header>
  <div class="main">
    <div class="container">
      <?php
      $aBreadCrumbs[0] = ['url' => Hl::url('contacts'), 'name' => Hl::$t->_('Contacts')];
      include(__DIR__ . "/../common/breadcrumbs.php"); ?>

      <div class="map">
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d10410.715436997963!2d23.498779484080323!3d49.28248211059344!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x6d73242be806805a!2z0KHQsNC90LDRgtC-0YDQuNC4INCi0YDRg9GB0LrQsNCy0YbQsA!5e0!3m2!1sru!2sru!4v1464636870281"
          width="100%" height="478" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>

      <section class="our-contacts">
        <h2 class="text-center"><?= Hl::$t->_('Contacts') ?></h2>
        <div class="arrow-down clearfix">
          <div class="inner-arrow"></div>
        </div>
        <div class="row">
          <div class="col-md-4 clearfix">
            <div class="address_icon_wr pull-left">
              <i class="fa fa-map-marker"></i>
            </div>
            <div class="address_content pull-left">
              <p><?= Hl::$t->_(Hl::opt('adres_info_1' . Hl::$pstfx)) ?></p>
              <p><?= Hl::$t->_(Hl::opt('adres_info_2' . Hl::$pstfx)) ?></p>
            </div>
          </div>
          <div class="col-md-4 clearfix">
            <div class="mobile_icon_wr pull-left">
              <i class="fa fa-mobile"></i>
            </div>
            <div class="mobile_content pull-left">
              <p><?= Hl::$t->_('free call') ?></p>
              <p><?= Hl::opt('free_phone') ?></p>
            </div>
          </div>
          <div class="col-md-4 clearfix">
            <div class="email_icon_wr pull-left">
              <i class="fa fa-envelope-o" aria-hidden="true"></i>
            </div>
            <div class="email_content pull-left">
              <p><?= Hl::opt('e-mail') ?></p>
            </div>
          </div>
        </div>
      </section>

    </div>
    <?php include(__DIR__ . '/../default/block_b_sec_10.php'); ?>
  </div>
  <footer>
    <?php include(__DIR__ . '/../common/footer.php'); ?>
  </footer>
  <?php include(__DIR__ . '/../common/footer_js.php'); ?>
