<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("actions", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit actions
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "actions/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNameUk" class="col-sm-2 control-label">Name Of Uk</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name_uk", "size" => 30, "class" => "form-control", "id" => "fieldNameUk")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSmallNote" class="col-sm-2 control-label">Small Of Note</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("small_note", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldSmallNote")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSmallNoteUk" class="col-sm-2 control-label">Small Of Note Of Uk</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("small_note_uk", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldSmallNoteUk")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNote" class="col-sm-2 control-label">Note</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("note", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldNote")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNoteUk" class="col-sm-2 control-label">Note Of Uk</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("note_uk", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldNoteUk")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPictureId" class="col-sm-2 control-label">Picture</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("picture_id", "type" => "number", "class" => "form-control", "id" => "fieldPictureId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldObjId" class="col-sm-2 control-label">Obj</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("obj_id", "type" => "number", "class" => "form-control", "id" => "fieldObjId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAttrId" class="col-sm-2 control-label">Attr</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("attr_id", "type" => "number", "class" => "form-control", "id" => "fieldAttrId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldVisible" class="col-sm-2 control-label">Visible</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("visible", "type" => "number", "class" => "form-control", "id" => "fieldVisible")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPercent" class="col-sm-2 control-label">Percent</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("percent", "type" => "number", "class" => "form-control", "id" => "fieldPercent")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateF" class="col-sm-2 control-label">Date Of F</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("date_f", "type" => "date", "class" => "form-control", "id" => "fieldDateF")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateE" class="col-sm-2 control-label">Date Of E</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("date_e", "type" => "date", "class" => "form-control", "id" => "fieldDateE")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTrash" class="col-sm-2 control-label">Trash</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("trash", "type" => "number", "class" => "form-control", "id" => "fieldTrash")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
