<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("actions/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("actions/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Name Of Uk</th>
            <th>Small Of Note</th>
            <th>Small Of Note Of Uk</th>
            <th>Note</th>
            <th>Note Of Uk</th>
            <th>Picture</th>
            <th>Obj</th>
            <th>Attr</th>
            <th>Visible</th>
            <th>Percent</th>
            <th>Date Of F</th>
            <th>Date Of E</th>
            <th>Trash</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $action): ?>
            <tr>
                <td><?php echo $action->id ?></td>
            <td><?php echo $action->name ?></td>
            <td><?php echo $action->name_uk ?></td>
            <td><?php echo $action->small_note ?></td>
            <td><?php echo $action->small_note_uk ?></td>
            <td><?php echo $action->note ?></td>
            <td><?php echo $action->note_uk ?></td>
            <td><?php echo $action->picture_id ?></td>
            <td><?php echo $action->obj_id ?></td>
            <td><?php echo $action->attr_id ?></td>
            <td><?php echo $action->visible ?></td>
            <td><?php echo $action->percent ?></td>
            <td><?php echo $action->date_f ?></td>
            <td><?php echo $action->date_e ?></td>
            <td><?php echo $action->trash ?></td>

                <td><?php echo $this->tag->linkTo(array("actions/edit/" . $action->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("actions/delete/" . $action->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("actions/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("actions/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("actions/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("actions/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
