<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("users/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("users/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Facebook</th>
            <th>Facebook Of Name</th>
            <th>Facebook Of Data</th>
            <th>Linkedin</th>
            <th>Linkedin Of Name</th>
            <th>Linkedin Of Data</th>
            <th>Gplus</th>
            <th>Gplus Of Name</th>
            <th>Gplus Of Data</th>
            <th>Twitter</th>
            <th>Twitter Of Name</th>
            <th>Twitter Of Data</th>
            <th>Must Of Change Of Password</th>
            <th>Profile</th>
            <th>Group</th>
            <th>Banned</th>
            <th>Suspended</th>
            <th>Active</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->id ?></td>
            <td><?php echo $user->name ?></td>
            <td><?php echo $user->email ?></td>
            <td><?php echo $user->password ?></td>
            <td><?php echo $user->facebook_id ?></td>
            <td><?php echo $user->facebook_name ?></td>
            <td><?php echo $user->facebook_data ?></td>
            <td><?php echo $user->linkedin_id ?></td>
            <td><?php echo $user->linkedin_name ?></td>
            <td><?php echo $user->linkedin_data ?></td>
            <td><?php echo $user->gplus_id ?></td>
            <td><?php echo $user->gplus_name ?></td>
            <td><?php echo $user->gplus_data ?></td>
            <td><?php echo $user->twitter_id ?></td>
            <td><?php echo $user->twitter_name ?></td>
            <td><?php echo $user->twitter_data ?></td>
            <td><?php echo $user->must_change_password ?></td>
            <td><?php echo $user->profile_id ?></td>
            <td><?php echo $user->group_id ?></td>
            <td><?php echo $user->banned ?></td>
            <td><?php echo $user->suspended ?></td>
            <td><?php echo $user->active ?></td>

                <td><?php echo $this->tag->linkTo(array("users/edit/" . $user->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("users/delete/" . $user->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("users/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("users/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("users/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("users/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
