<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search tours
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("tours/new", "Create tours")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "tours/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id", "type" => "number", "class" => "form-control", "id" => "fieldId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAttrId" class="col-sm-2 control-label">Attr</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("attr_id", "type" => "number", "class" => "form-control", "id" => "fieldAttrId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserId" class="col-sm-2 control-label">User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("user_id", "type" => "number", "class" => "form-control", "id" => "fieldUserId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPlaceId" class="col-sm-2 control-label">Place</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("place_id", "type" => "number", "class" => "form-control", "id" => "fieldPlaceId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPictureId" class="col-sm-2 control-label">Picture</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("picture_id", "type" => "number", "class" => "form-control", "id" => "fieldPictureId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNameUk" class="col-sm-2 control-label">Name Of Uk</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name_uk", "size" => 30, "class" => "form-control", "id" => "fieldNameUk")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSmallNote" class="col-sm-2 control-label">Small Of Note</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("small_note", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldSmallNote")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSmallNoteUk" class="col-sm-2 control-label">Small Of Note Of Uk</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("small_note_uk", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldSmallNoteUk")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNote" class="col-sm-2 control-label">Note</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("note", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldNote")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNoteUk" class="col-sm-2 control-label">Note Of Uk</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("note_uk", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldNoteUk")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("price", "type" => "number", "class" => "form-control", "id" => "fieldPrice")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDays" class="col-sm-2 control-label">Days</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("days", "type" => "number", "class" => "form-control", "id" => "fieldDays")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTrash" class="col-sm-2 control-label">Trash</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("trash", "type" => "number", "class" => "form-control", "id" => "fieldTrash")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
