<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("tables", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit tables
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "tables/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAdmLink" class="col-sm-2 control-label">Adm Of Link</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("adm_link", "size" => 30, "class" => "form-control", "id" => "fieldAdmLink")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNote" class="col-sm-2 control-label">Note</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("note", "size" => 30, "class" => "form-control", "id" => "fieldNote")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNoteUk" class="col-sm-2 control-label">Note Of Uk</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("note_uk", "size" => 30, "class" => "form-control", "id" => "fieldNoteUk")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImg" class="col-sm-2 control-label">Img</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("img", "size" => 30, "class" => "form-control", "id" => "fieldImg")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMultilang" class="col-sm-2 control-label">Multilang</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("multilang", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldMultilang")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSystem" class="col-sm-2 control-label">System</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("system", "type" => "number", "class" => "form-control", "id" => "fieldSystem")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserinfo" class="col-sm-2 control-label">Userinfo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("userinfo", "type" => "number", "class" => "form-control", "id" => "fieldUserinfo")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHasFeed" class="col-sm-2 control-label">Has Of Feed</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("has_feed", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldHasFeed")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLinkField" class="col-sm-2 control-label">Link Of Field</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("link_field", "size" => 30, "class" => "form-control", "id" => "fieldLinkField")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
