<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("tables/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("tables/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Adm Of Link</th>
            <th>Note</th>
            <th>Note Of Uk</th>
            <th>Img</th>
            <th>Multilang</th>
            <th>System</th>
            <th>Userinfo</th>
            <th>Has Of Feed</th>
            <th>Link Of Field</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $table): ?>
            <tr>
                <td><?php echo $table->id ?></td>
            <td><?php echo $table->name ?></td>
            <td><?php echo $table->adm_link ?></td>
            <td><?php echo $table->note ?></td>
            <td><?php echo $table->note_uk ?></td>
            <td><?php echo $table->img ?></td>
            <td><?php echo $table->multilang ?></td>
            <td><?php echo $table->system ?></td>
            <td><?php echo $table->userinfo ?></td>
            <td><?php echo $table->has_feed ?></td>
            <td><?php echo $table->link_field ?></td>

                <td><?php echo $this->tag->linkTo(array("tables/edit/" . $table->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("tables/delete/" . $table->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("tables/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("tables/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("tables/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("tables/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
