<?php include(__DIR__."/../common/doctype.php"); ?>
<head>
  <?php include(__DIR__."/../common/head.php"); ?>
</head>
<body>
<div class="wrapp product_category">
  <header>
    <div class="container">
        <?php include(__DIR__."/../common/header.php"); ?>
    </div>
  </header>
  <section class="main_content">
    <div class="container">
      <?php
        echo $this->getContent();
        echo $this->flashSession->output();

        echo $this->tag->form(
          array(
            Hl::url('user/forgotPassword'),
            "autocomplete" => "off",
            "class" => "form-horizontal"
          )
        );
        echo $form->render('email');
        echo $form->render('Send');
        echo $this->tag->endForm();
      ?>
    </div>
  </section>

</div>
<footer>
  <?php include(__DIR__.'/../common/footer.php'); ?>
</footer>
<?php include(__DIR__.'/../common/footer_js.php'); ?>
</body>
