<?php include(__DIR__."/../common/doctype.php"); ?>
<head>
  <?php include(__DIR__."/../common/head.php"); ?>
</head>
<body>
<div class="wrapp product_category">
  <header>
    <div class="container">
        <?php include(__DIR__."/../common/header.php"); ?>
    </div>
  </header>
  <section class="main_content">
    <div class="container">
      <?php echo $this->getContent(); ?>

      <div class="row">
        <table class="table table-bordered">
          <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Group</th>
            <th>Banned</th>
            <th>Suspended</th>
            <th>Active</th>
            <th></th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <?php foreach ($page->items as $user): ?>
            <tr>
              <td><?php echo $user->id ?></td>
              <td><?php echo $user->name ?></td>
              <td><?php echo $user->email ?></td>
              <td><?php echo $user->group_id ?></td>
              <td><?php echo $user->banned ?></td>
              <td><?php echo $user->suspended ?></td>
              <td><?php echo $user->active ?></td>

              <td><?php echo $this->tag->linkTo(array("user/edit/" . $user->id, "Edit")); ?></td>
              <td><?php echo $this->tag->linkTo(array("user/delete/" . $user->id, "Delete")); ?></td>
            </tr>
          <?php endforeach; ?>
          </tbody>
        </table>
      </div>
      <div class="row">
        <div class="col-sm-1">
          <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
          </p>
        </div>
        <div class="col-sm-11">
          <nav>
            <ul class="pagination">
              <li><?php echo $this->tag->linkTo("user/list", "First") ?></li>
              <li><?php echo $this->tag->linkTo("user/list?page=" . $page->before, "Previous") ?></li>
              <li><?php echo $this->tag->linkTo("user/list?page=" . $page->next, "Next") ?></li>
              <li><?php echo $this->tag->linkTo("user/list?page=" . $page->last, "Last") ?></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </section>

</div>
<footer>
  <?php include(__DIR__.'/../common/footer.php'); ?>
</footer>
<?php include(__DIR__.'/../common/footer_js.php'); ?>
</body>
