<?php include(__DIR__."/../common/doctype.php"); ?>
<head>
  <?php include(__DIR__."/../common/head.php"); ?>
</head>
<body>
<div class="wrapp product_category">
  <header>
    <div class="container">
        <?php include(__DIR__."/../common/header.php"); ?>
    </div>
  </header>
  <section class="main_content">
    <div class="container">
      <?php
        echo $this->getContent();
        echo $this->flashSession->output();

        echo $this->tag->form(
          array(
            Hl::url('user/register'),
            "autocomplete" => "off",
            "class" => "form-horizontal"
          )
        );
        // Проходимо полями форми
        foreach ($form as $element) {

          // Собираем все сгенерированные сообщения для текущего элемента
          $messages = $form->getMessagesFor($element->getName());

          if (count($messages)) {
            // Выводим каждый элемент
            echo '<div class="messages">';
            foreach ($messages as $message) {
              echo $message;
            }
            echo '</div>';
          }

          echo '<p>';
          echo '<label for="', $element->getName(), '">', $element->getLabel(), '</label>';
          echo $element;
          echo '</p>';

        }
        echo $this->tag->endForm();
      ?>
    </div>
  </section>

</div>
<footer>
  <?php include(__DIR__.'/../common/footer.php'); ?>
</footer>
<?php include(__DIR__.'/../common/footer_js.php'); ?>
</body>
