<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("pictures/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("pictures/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Obj</th>
            <th>Attr</th>
            <th>User</th>
            <th>Path</th>
            <th>Note</th>
            <th>Note Of Uk</th>
            <th>Alt</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $picture): ?>
            <tr>
                <td><?php echo $picture->id ?></td>
            <td><?php echo $picture->obj_id ?></td>
            <td><?php echo $picture->attr_id ?></td>
            <td><?php echo $picture->user_id ?></td>
            <td><?php echo $picture->path ?></td>
            <td><?php echo $picture->note ?></td>
            <td><?php echo $picture->note_uk ?></td>
            <td><?php echo $picture->alt ?></td>

                <td><?php echo $this->tag->linkTo(array("pictures/edit/" . $picture->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("pictures/delete/" . $picture->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("pictures/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("pictures/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("pictures/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("pictures/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
