<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("feedbacks/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("feedbacks/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>User</th>
            <th>Attr</th>
            <th>Obj</th>
            <th>Note</th>
            <th>Note Of Uk</th>
            <th>Likeit</th>
            <th>Created</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $feedback): ?>
            <tr>
                <td><?php echo $feedback->id ?></td>
            <td><?php echo $feedback->user_id ?></td>
            <td><?php echo $feedback->attr_id ?></td>
            <td><?php echo $feedback->obj_id ?></td>
            <td><?php echo $feedback->note ?></td>
            <td><?php echo $feedback->note_uk ?></td>
            <td><?php echo $feedback->likeit ?></td>
            <td><?php echo $feedback->created ?></td>

                <td><?php echo $this->tag->linkTo(array("feedbacks/edit/" . $feedback->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("feedbacks/delete/" . $feedback->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("feedbacks/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("feedbacks/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("feedbacks/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("feedbacks/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
