<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("rooms", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit rooms
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "rooms/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldHotelId" class="col-sm-2 control-label">Hotel</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("hotel_id", "type" => "number", "class" => "form-control", "id" => "fieldHotelId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNameUk" class="col-sm-2 control-label">Name Of Uk</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name_uk", "size" => 30, "class" => "form-control", "id" => "fieldNameUk")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("price", "type" => "number", "class" => "form-control", "id" => "fieldPrice")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAttrId" class="col-sm-2 control-label">Attr</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("attr_id", "type" => "number", "class" => "form-control", "id" => "fieldAttrId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPictureId" class="col-sm-2 control-label">Picture</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("picture_id", "type" => "number", "class" => "form-control", "id" => "fieldPictureId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNote" class="col-sm-2 control-label">Note</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("note", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldNote")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNoteUk" class="col-sm-2 control-label">Note Of Uk</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("note_uk", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldNoteUk")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCnt" class="col-sm-2 control-label">Cnt</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cnt", "type" => "number", "class" => "form-control", "id" => "fieldCnt")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAdult" class="col-sm-2 control-label">Adult</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("adult", "type" => "number", "class" => "form-control", "id" => "fieldAdult")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldChild" class="col-sm-2 control-label">Child</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("child", "type" => "number", "class" => "form-control", "id" => "fieldChild")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTrash" class="col-sm-2 control-label">Trash</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("trash", "type" => "number", "class" => "form-control", "id" => "fieldTrash")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
