<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("rooms/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("rooms/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Hotel</th>
            <th>Name</th>
            <th>Name Of Uk</th>
            <th>Price</th>
            <th>Attr</th>
            <th>Picture</th>
            <th>Note</th>
            <th>Note Of Uk</th>
            <th>Cnt</th>
            <th>Adult</th>
            <th>Child</th>
            <th>Trash</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $room): ?>
            <tr>
                <td><?php echo $room->id ?></td>
            <td><?php echo $room->hotel_id ?></td>
            <td><?php echo $room->name ?></td>
            <td><?php echo $room->name_uk ?></td>
            <td><?php echo $room->price ?></td>
            <td><?php echo $room->attr_id ?></td>
            <td><?php echo $room->picture_id ?></td>
            <td><?php echo $room->note ?></td>
            <td><?php echo $room->note_uk ?></td>
            <td><?php echo $room->cnt ?></td>
            <td><?php echo $room->adult ?></td>
            <td><?php echo $room->child ?></td>
            <td><?php echo $room->trash ?></td>

                <td><?php echo $this->tag->linkTo(array("rooms/edit/" . $room->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("rooms/delete/" . $room->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("rooms/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("rooms/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("rooms/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("rooms/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
