<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag;

$mName = "attrtypes";
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?php echo $this->tag->linkTo( array( "{$mName}/index", "Go Back" ) ); ?></li>
			<li class="next"><?php echo $this->tag->linkTo( array( "{$mName}/new", "Create " ) ); ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h1><?= $this->tag->linkTo( Hl::url( "{$mName}/search" ), "Search result" ) ?></h1>
</div>

<?php echo $this->getContent(); ?>

<div class="col-md-12 col-sm-12 col-xs-12">
	<div class="x_panel">
		<div class="x_title">
			<h2>Fixed Header Example</h2>
			<ul class="nav navbar-right panel_toolbox">
				<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i
							class="fa fa-wrench"></i></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#">Settings 1</a>
						</li>
						<li><a href="#">Settings 2</a>
						</li>
					</ul>
				</li>
				<li><a class="close-link"><i class="fa fa-close"></i></a>
				</li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="x_content">
			<p class="text-muted font-13 m-b-30">
				This example shows FixedHeader being styling by the Bootstrap CSS framework.
			</p>
			<div id="datatable-fixed-header_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
				<div class="row">
					<div class="col-sm-6">
						<div class="dataTables_length" id="datatable-fixed-header_length"><label>Show <select
									name="datatable-fixed-header_length" aria-controls="datatable-fixed-header"
									class="form-control input-sm">
									<option value="10">10</option>
									<option value="25">25</option>
									<option value="50">50</option>
									<option value="100">100</option>
								</select> entries</label></div>
					</div>
					<div class="col-sm-6">
						<div id="datatable-fixed-header_filter" class="dataTables_filter"><label>Search:<input
									type="search" class="form-control input-sm" placeholder=""
									aria-controls="datatable-fixed-header"></label></div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<table id="datatable-fixed-header"
						       class="table table-striped table-bordered dataTable no-footer" role="grid"
						       aria-describedby="datatable-fixed-header_info">
							<thead>
							<tr>
								<?php
								$aFields = Attrtypes::fields();
								foreach ( $aFields as $l )
									echo '<th>' . $l[ 'label' ] . '</th>';
								?>
								<th>#Edit</th>
							</tr>
							</thead>
							<tbody>
							<tr>
								<td>0</td>
								<td>test</td>
								<td>test</td>
								<td>test</td>
								<td>test</td>
								<td>
									<a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
									<a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
									<a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
								</td>
							</tr>
							<?php foreach ( $page->items as $item ): ?>
								<tr>
									<?php
									$aItems = get_object_vars( $item );
									foreach ( $aFields as $k => $l )
										echo '<td>' . $aItems[ $k ] . '</td>';
									?>
									<td><?php echo $this->tag->linkTo( array( Hl::url( "$mName/edit/" . $item->id ), "Edit" ) ); ?></td>
									<td><?php echo $this->tag->linkTo( array( Hl::url( "$mName/delete/" . $item->id ), "Delete" ) ); ?></td>
								</tr>
							<?php endforeach; ?>
							</tbody>
						</table>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-5">
						<div class="dataTables_info" id="datatable-fixed-header_info" role="status" aria-live="polite">
							Showing <?php echo $page->current, "/", $page->total_pages ?> entries
						</div>
					</div>
					<div class="col-sm-7">
						<div class="dataTables_paginate paging_simple_numbers" id="datatable-fixed-header_paginate">
							<ul class="pagination">
								<li class="paginate_button previous disabled" id="datatable-fixed-header_previous"><a
										href="#" aria-controls="datatable-fixed-header" data-dt-idx="0" tabindex="0">Previous</a>
								</li>
								<li class="paginate_button active"><a href="#" aria-controls="datatable-fixed-header"
								                                      data-dt-idx="1" tabindex="0">1</a></li>
								<li class="paginate_button "><a href="#" aria-controls="datatable-fixed-header"
								                                data-dt-idx="2" tabindex="0">2</a></li>
								<li class="paginate_button "><a href="#" aria-controls="datatable-fixed-header"
								                                data-dt-idx="3" tabindex="0">3</a></li>
								<li class="paginate_button "><a href="#" aria-controls="datatable-fixed-header"
								                                data-dt-idx="4" tabindex="0">4</a></li>
								<li class="paginate_button "><a href="#" aria-controls="datatable-fixed-header"
								                                data-dt-idx="5" tabindex="0">5</a></li>
								<li class="paginate_button "><a href="#" aria-controls="datatable-fixed-header"
								                                data-dt-idx="6" tabindex="0">6</a></li>
								<li class="paginate_button next" id="datatable-fixed-header_next"><a href="#"
								                                                                     aria-controls="datatable-fixed-header"
								                                                                     data-dt-idx="7"
								                                                                     tabindex="0">Next</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-1">
		<p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
			<?php echo $page->current, "/", $page->total_pages ?>
		</p>
	</div>
	<div class="col-sm-11">
		<nav>
			<ul class="pagination">
				<?php if ( $page->current > 1 && $page->total_pages > 1 ) { ?>
					<li><?php echo $this->tag->linkTo( Hl::url( "$mName" ), "First" ) ?></li>
					<li><?php echo $this->tag->linkTo( Hl::url( "$mName?page=" . $page->before ), "Previous" ) ?></li>
				<?php } ?>
				<?php if ( $page->current < $page->total_pages ) { ?>
					<li><?php echo $this->tag->linkTo( Hl::url( "$mName?page=" . $page->next ), "Next" ) ?></li>
					<li><?php echo $this->tag->linkTo( Hl::url( "$mName?page=" . $page->last ), "Last" ) ?></li>
				<?php } ?>
			</ul>
		</nav>
	</div>
</div>
