<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("blog/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("blog/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>User</th>
            <th>Attr</th>
            <th>Picture</th>
            <th>Title</th>
            <th>Title Of Uk</th>
            <th>Small Of Note</th>
            <th>Small Of Note Of Uk</th>
            <th>Note</th>
            <th>Note Of Uk</th>
            <th>Created</th>
            <th>Trash</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $blog): ?>
            <tr>
                <td><?php echo $blog->id ?></td>
            <td><?php echo $blog->user_id ?></td>
            <td><?php echo $blog->attr_id ?></td>
            <td><?php echo $blog->picture_id ?></td>
            <td><?php echo $blog->title ?></td>
            <td><?php echo $blog->title_uk ?></td>
            <td><?php echo $blog->small_note ?></td>
            <td><?php echo $blog->small_note_uk ?></td>
            <td><?php echo $blog->note ?></td>
            <td><?php echo $blog->note_uk ?></td>
            <td><?php echo $blog->created ?></td>
            <td><?php echo $blog->trash ?></td>

                <td><?php echo $this->tag->linkTo(array("blog/edit/" . $blog->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("blog/delete/" . $blog->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("blog/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("blog/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("blog/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("blog/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
