<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search langs
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("langs/new", "Create langs")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "langs/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id", "type" => "number", "class" => "form-control", "id" => "fieldId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLang" class="col-sm-2 control-label">Lang</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("lang", "size" => 30, "class" => "form-control", "id" => "fieldLang")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCurrency" class="col-sm-2 control-label">Currency</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("currency", "type" => "number", "class" => "form-control", "id" => "fieldCurrency")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDef" class="col-sm-2 control-label">Def</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("def", "type" => "number", "class" => "form-control", "id" => "fieldDef")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTrash" class="col-sm-2 control-label">Trash</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("trash", "type" => "number", "class" => "form-control", "id" => "fieldTrash")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
