<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php //include(__DIR__.'/../common/p_top.php'); ?>
<section class="main_content">
    <div class="container">
        <?php echo $this->getContent(); ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("hotels", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit hotels
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "hotels/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<?php include 'fields.phtml'; ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

  </div>
</section>

<?php //include(__DIR__.'/../common/p_bottom.php'); ?>
