<?php use Phalcon\Tag as Tag; ?>
<?php include(__DIR__."/common/doctype.php"); ?>
<head>
  <?php include(__DIR__."/common/head.php"); ?>
</head>
        <?php
//        echo __FILE__;

        echo $this->getContent();

        /*$this->assets
          ->addJs('public/js/jquery.min.js')
          ->addJs('public/bootstrap/js/bootstrap.js')
          ->addJs('public/js/prettify/prettify.js');*/
        $this->assets->outputJs(); ?>
</html>